### ISSUE TITLE
Bug: Spoiler block renders incorrectly inside of callouts

### ISSUE THREAD

**Issue by Trikzon** [jacobtread/obsidian-spoilers#1]
**Describe the bug**

**To Reproduce**

Place the following markdown in a file and render it
```md
> [!info]
> ```spoiler
> Test
> ```
```

**Expected behavior**

The text should be hidden.

**Screenshots**

![image](https://github.com/user-attachments/assets/1dbef520-b02f-437b-b1d8-31a3ea2512cb)
The text is not hidden when it should be inside of a callout.

**Additional context**

**Comment by jacobtread** [comment]
Fix published in latest release, looks like some weird behavior with the blur not working within callouts so have just made the cover a solid black within callouts.
