### ISSUE TITLE
Bug: Spoiler markdown rendering when hidden

### ISSUE THREAD

**Issue by Panthon13** [jacobtread/obsidian-spoilers#3]
**Describe the bug**
Using lists, either with hyphens or numbers, show through the spoiler-markdown window.

**To Reproduce**
Use this in a note as an example:

```spoiler-markdown
## Heading

**Xaelith’s Role**:  
1. This is a number.
2. This is the second.

- This is a bullet
- This is another
```

**Expected behavior**
All (supported) markdown content should be hidden behind the spoiler window.

**Screenshots**
![Screenshot 2024-10-03 143513](https://github.com/user-attachments/assets/a5e1e367-0526-4be9-b543-f490ff20e6e3)

**Additional context**
I'm on the latest version of the plugin and of Obsidian on Windows 11.. This issue also occurs on my iPad with the same markdown.

**Comment by jacobtread** [comment]
Fixed in 1.0.4
